version: '3'
services:
  restaurant_backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_backend
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "python /app/restaurant_backend/manage.py makemigrations && python /app/restaurant_backend/manage.py migrate && python /app/restaurant_backend/manage.py runserver"

volumes:
  .:
