name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Deploy-to-VPS:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Stop and delete container
        run: docker stop restaurant_backend
      - run: docker rm -f restaurant_backend
      - name: Delete image
        run: docker rmi -f restaurant_backend_image
      - name: Create env file 
        run: |
          touch .env
          echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
          echo DEBUG="${{ secrets.DEBUG }}" >> .env
          echo ALLOWED_HOSTS="${{ secrets.ALLOWED_HOSTS }}" >> .env
          echo DB_ENGINE="${{ secrets.DB_ENGINE }}" >> .env
          echo DB_NAME="${{ secrets.DB_NAME }}" >> .env
          echo DB_USER="${{ secrets.DB_USER }}" >> .env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> .env
          echo DB_HOST="${{ secrets.DB_HOST }}" >> .env
          echo DB_PORT="${{ secrets.DB_PORT }}" >> .env
          echo CSRF_TRUSTED_ORIGINS="${{ secrets.CSRF_TRUSTED_ORIGINS }}" >> .env
      - name: Exec container
        run: docker-compose up -d
